-- liquibase formatted sql

-- changeset jyyoon:1692775610335-1
CREATE TABLE public."user" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), CONSTRAINT "userPK" PRIMARY KEY (id));

